kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim
  labels:
    uid: 1500
    gid: 1500
spec:
  storageClassName: "managed-nfs-storage"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi

